spring.application.name=backend
2
 
3
spring.datasource.url=jdbc:postgresql://localhost:5432/taller_patinetas
4
spring.datasource.username=postgres
5
spring.datasource.password=Ye1s0n.14
6
 
7
spring.jpa.hibernate.ddl-auto=update
8
spring.jpa.show-sql=true
9
spring.jpa.properties.hibernate.format_sql=true